from .turnaround_splitter import NODE_CLASS_MAPPINGS as _SPLIT_MAP, NODE_DISPLAY_NAME_MAPPINGS as _SPLIT_NAMES
from .scale_mesh_axis import NODE_CLASS_MAPPINGS as _SCALE_MAP, NODE_DISPLAY_NAME_MAPPINGS as _SCALE_NAMES

NODE_CLASS_MAPPINGS = {**_SPLIT_MAP, **_SCALE_MAP}
NODE_DISPLAY_NAME_MAPPINGS = {**_SPLIT_NAMES, **_SCALE_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
